[
  {
    "combo_id": 1,
    "combo_name": "Asian Fusion Delight",
    "combo_item_ids": [
      "71",
      "131",
      "87"
    ],
    "cost": 1450,
    "description": "A harmonious blend of sweet, spicy, and savory flavors from across Asian cuisines.",
    "discount_pct": 5,
    "discounted_cost": 1377.5,
    "has_discount": "yes",
    "combo_type": "premium",
    "combo_items": [
      {
        "item_id": 71,
        "restaurant_id": 63471,
        "number_of_people_rated": 25,
        "category": "Small Plates - Asian Non-veg",
        "name_of_item": "Mongolian Beef",
        "cost": 610,
        "rating": 4.4,
        "description": "Slices of flank steak, cooked in a homemade Mongolian inspired sauce, soya sauce, onions & bell peppers",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/53b/9fe6186ba6ba721c9da77325ebf9753b.jpeg",
        "ingredients": "flank steak, homemade mongolian sauce, soya sauce, onions, bell peppers",
        "protein": "high",
        "fat": "medium",
        "energy": "medium",
        "carbohydrates": "low",
        "sugar_content": "absent",
        "fiber": "low",
        "veg_or_non_veg": "non-veg",
        "spiciness": "not spicy",
        "cuisine": "other asian",
        "meal_time": "lunch or dinner",
        "health_concious_option": "no",
        "allergens_present": "soy",
        "contains_chicken": "no",
        "contains_beef": "yes",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "yes",
        "is_gluten_free": "not applicable",
        "is_keto_friendly": "yes",
        "is_low_gi": "not applicable",
        "meal_course_type": "small plates"
      },
      {
        "item_id": 131,
        "restaurant_id": 63471,
        "number_of_people_rated": 81,
        "category": "Small Plates - Asian Veg",
        "name_of_item": "Thai Style Crispy Lotus Stem",
        "cost": 430,
        "rating": 4.3,
        "description": "Fried lotus stems tossed in a sweet & spicy Thai chilli sauce",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/2b1/5ba328f9b1ebb3e4beb810dc92f462b1.jpeg",
        "ingredients": "lotus stems, thai chilli sauce, sweet sauce, spicy sauce, oil",
        "protein": "absent",
        "fat": "medium",
        "energy": "medium",
        "carbohydrates": "medium",
        "sugar_content": "medium",
        "fiber": "high",
        "veg_or_non_veg": "veg",
        "spiciness": "spicy",
        "cuisine": "thai",
        "meal_time": "snacks",
        "health_concious_option": "no",
        "allergens_present": "not applicable",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "yes",
        "is_sattvic": "not applicable",
        "is_jain_food": "not applicable",
        "is_dairy_free": "yes",
        "is_gluten_free": "not sure",
        "is_keto_friendly": "no",
        "is_low_gi": "not applicable",
        "meal_course_type": "small plates"
      },
      {
        "item_id": 87,
        "restaurant_id": 63471,
        "number_of_people_rated": null,
        "category": "Large Plates - Asian Rice & Noodles",
        "name_of_item": "Phad Thai",
        "cost": 410,
        "rating": null,
        "description": "Thai stir-fried noodle dish, featuring rice noodles tossed with tofu or shrimp and peanuts in a tangy tamarind sauce.",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/854/71d94f18af3ae019ddd17e21a1346854.jpeg",
        "ingredients": "rice noodles, tofu, shrimp, peanuts, tamarind sauce, vegetables",
        "protein": "medium",
        "fat": "medium",
        "energy": "high",
        "carbohydrates": "high",
        "sugar_content": "low",
        "fiber": "medium",
        "veg_or_non_veg": "non-veg",
        "spiciness": "not spicy",
        "cuisine": "thai",
        "meal_time": "lunch or dinner",
        "health_concious_option": "yes",
        "allergens_present": "peanuts",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "yes",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "yes",
        "is_gluten_free": "not applicable",
        "is_keto_friendly": "no",
        "is_low_gi": "no",
        "meal_course_type": "main course"
      }
    ]
  },
  {
    "combo_id": 2,
    "combo_name": "Italian Comfort",
    "combo_item_ids": [
      "84",
      "4",
      "122"
    ],
    "cost": 2460,
    "description": "A comforting and indulgent Italian-inspired meal with creamy textures and robust flavors.",
    "discount_pct": 10,
    "discounted_cost": 2214,
    "has_discount": "yes",
    "combo_type": "vip",
    "combo_items": [
      {
        "item_id": 84,
        "restaurant_id": 63471,
        "number_of_people_rated": null,
        "category": "Pasta & Risotto",
        "name_of_item": "Penne Pasta",
        "cost": 500,
        "rating": null,
        "description": "ALFREDO | ARRABIATA | AGLIO E OLIO | BASIL PESTO",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/0f2/26885fcc01d3852eecd6ca3f8f02d0f2.jpeg",
        "ingredients": "penne pasta, alfredo sauce, arrabiata sauce, aglio e olio, basil pesto",
        "protein": "low",
        "fat": "medium",
        "energy": "medium",
        "carbohydrates": "high",
        "sugar_content": "absent",
        "fiber": "low",
        "veg_or_non_veg": "veg",
        "spiciness": "not spicy",
        "cuisine": "italian",
        "meal_time": "lunch or dinner",
        "health_concious_option": "no",
        "allergens_present": "dairy, gluten",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "yes",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "no",
        "is_gluten_free": "no",
        "is_keto_friendly": "no",
        "is_low_gi": "no",
        "meal_course_type": "main course"
      },
      {
        "item_id": 4,
        "restaurant_id": 63471,
        "number_of_people_rated": 7,
        "category": "Pasta & Risotto",
        "name_of_item": "Assorted Mushroom Risotto",
        "cost": 540,
        "rating": 3.6,
        "description": "Arborio rice cooked with porcini, oyster & shiitake mushrooms, truffle oil",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/b24/beed16669206bd3daf3860571d55eb24.jpeg",
        "ingredients": "arborio rice, porcini mushrooms, oyster mushrooms, shiitake mushrooms, truffle oil",
        "protein": "low",
        "fat": "medium",
        "energy": "medium",
        "carbohydrates": "high",
        "sugar_content": "absent",
        "fiber": "medium",
        "veg_or_non_veg": "veg",
        "spiciness": "not spicy",
        "cuisine": "italian",
        "meal_time": "lunch or dinner",
        "health_concious_option": "yes",
        "allergens_present": "mushrooms",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "yes",
        "is_gluten_free": "not applicable",
        "is_keto_friendly": "no",
        "is_low_gi": "no",
        "meal_course_type": "main course"
      },
      {
        "item_id": 122,
        "restaurant_id": 63471,
        "number_of_people_rated": 58,
        "category": "Grill - Beef",
        "name_of_item": "T-bone Steak",
        "cost": 1420,
        "rating": 4.8,
        "description": "Grilled T-bone steak (beef), Mixed Green Salad, Roasted potato & jus; RARE | MEDIUM RARE | MEDIUM | MEDIUM WELL | WELL DONE",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/7fd/e7784068338a3d542891ca9cceb7e7fd.jpeg",
        "ingredients": "grilled t-bone steak, beef, mixed green salad, roasted potato, jus, rare, medium rare, medium, medium well, well done",
        "protein": "high",
        "fat": "medium",
        "energy": "high",
        "carbohydrates": "low",
        "sugar_content": "absent",
        "fiber": "low",
        "veg_or_non_veg": "non-veg",
        "spiciness": "not applicable",
        "cuisine": "american",
        "meal_time": "dinner",
        "health_concious_option": "no",
        "allergens_present": "none",
        "contains_chicken": "no",
        "contains_beef": "yes",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "yes",
        "is_gluten_free": "not applicable",
        "is_keto_friendly": "yes",
        "is_low_gi": "not applicable",
        "meal_course_type": "main course"
      }
    ]
  },
  {
    "combo_id": 3,
    "combo_name": "Asian Veg Extravaganza",
    "combo_item_ids": [
      "114",
      "2",
      "48"
    ],
    "cost": 1170,
    "description": "A vegetarian-friendly combination with deep, savory Asian flavors and a spicy kick.",
    "discount_pct": 0,
    "discounted_cost": 1170,
    "has_discount": "no",
    "combo_type": "standard",
    "combo_items": [
      {
        "item_id": 114,
        "restaurant_id": 63471,
        "number_of_people_rated": 68,
        "category": "Small Plates - Asian Veg",
        "name_of_item": "Spicy Crispy Tofu",
        "cost": 430,
        "rating": 4.4,
        "description": "Deep fried tofu, tossed with Chilli garlic crumb",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/c34/2e435cd9510da7fc68548bf78516dc34.jpeg",
        "ingredients": "tofu, chilli, garlic, crumb",
        "protein": "medium",
        "fat": "medium",
        "energy": "medium",
        "carbohydrates": "low",
        "sugar_content": "absent",
        "fiber": "low",
        "veg_or_non_veg": "veg",
        "spiciness": "spicy",
        "cuisine": "other asian",
        "meal_time": "snacks",
        "health_concious_option": "yes",
        "allergens_present": "tofu",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "yes",
        "is_sattvic": "not applicable",
        "is_jain_food": "not applicable",
        "is_dairy_free": "yes",
        "is_gluten_free": "not sure",
        "is_keto_friendly": "not sure",
        "is_low_gi": "not sure",
        "meal_course_type": "small plates"
      },
      {
        "item_id": 2,
        "restaurant_id": 63471,
        "number_of_people_rated": 28,
        "category": "Small Plates - Asian Veg",
        "name_of_item": "Asian Mushroom Pepper Fry",
        "cost": 430,
        "rating": 4.2,
        "description": "Mushrooms wok-tossed in a chilli & black pepper sauce",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/fe8/7c76897c9837f845f1cd6a79b9ef9fe8.jpeg",
        "ingredients": "mushrooms, chilli, black pepper, sauce",
        "protein": "low",
        "fat": "low",
        "energy": "medium",
        "carbohydrates": "low",
        "sugar_content": "absent",
        "fiber": "medium",
        "veg_or_non_veg": "veg",
        "spiciness": "moderately spicy",
        "cuisine": "other asian",
        "meal_time": "snacks",
        "health_concious_option": "yes",
        "allergens_present": "none",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "yes",
        "is_sattvic": "not applicable",
        "is_jain_food": "not applicable",
        "is_dairy_free": "yes",
        "is_gluten_free": "yes",
        "is_keto_friendly": "not sure",
        "is_low_gi": "not sure",
        "meal_course_type": "small plates"
      },
      {
        "item_id": 48,
        "restaurant_id": 63471,
        "number_of_people_rated": 74,
        "category": "Large Plates - Asian Rice & Noodles",
        "name_of_item": "Hakka Noodles",
        "cost": 310,
        "rating": 3.4,
        "description": "Stir-fried noodles, seasoned with savory sauces and spices. VEG | EGG | CHICKEN | SEAFOOD",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/03d/76936a400a7afc4dd18d188eff2d403d.jpeg",
        "ingredients": "hakka noodles, stir-fried noodles, savory sauces, spices, veg, egg, chicken, seafood",
        "protein": "medium",
        "fat": "medium",
        "energy": "high",
        "carbohydrates": "high",
        "sugar_content": "absent",
        "fiber": "low",
        "veg_or_non_veg": "veg",
        "spiciness": "not spicy",
        "cuisine": "chinese",
        "meal_time": "lunch or dinner",
        "health_concious_option": "no",
        "allergens_present": "egg, seafood",
        "contains_chicken": "yes",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "yes",
        "contains_pork": "no",
        "contains_egg": "yes",
        "contains_dairy": "no",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "yes",
        "is_gluten_free": "not applicable",
        "is_keto_friendly": "no",
        "is_low_gi": "not applicable",
        "meal_course_type": "main course"
      }
    ]
  },
  {
    "combo_id": 4,
    "combo_name": "American BBQ Feast",
    "combo_item_ids": [
      "106",
      "42",
      "93"
    ],
    "cost": 1535,
    "description": "A classic American BBQ meal with smoky, tender meats and satisfying sides.",
    "discount_pct": 5,
    "discounted_cost": 1458.25,
    "has_discount": "yes",
    "combo_type": "premium",
    "combo_items": [
      {
        "item_id": 106,
        "restaurant_id": 63471,
        "number_of_people_rated": 34,
        "category": "Grill - Pork",
        "name_of_item": "Slow Roasted Baby Back Pork Ribs",
        "cost": 730,
        "rating": 3.8,
        "description": "Grilled pork ribs, bbq sauce, corn ribs, grilled pineapple & apple",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/33c/04afc1ef4b45069cd7a94d9856ec433c.jpeg",
        "ingredients": "grilled pork ribs, bbq sauce, corn ribs, grilled pineapple, apple",
        "protein": "high",
        "fat": "high",
        "energy": "high",
        "carbohydrates": "medium",
        "sugar_content": "low",
        "fiber": "low",
        "veg_or_non_veg": "non-veg",
        "spiciness": "not applicable",
        "cuisine": "american",
        "meal_time": "dinner",
        "health_concious_option": "no",
        "allergens_present": "none",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "yes",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "yes",
        "is_gluten_free": "not applicable",
        "is_keto_friendly": "no",
        "is_low_gi": "not applicable",
        "meal_course_type": "main course"
      },
      {
        "item_id": 42,
        "restaurant_id": 63471,
        "number_of_people_rated": null,
        "category": "Bar Nibbles Veg",
        "name_of_item": "Fries",
        "cost": 295,
        "rating": null,
        "description": "French Fries dusted with Cheddar Cheese Seasoning, Tartar sauce & Pickled mayo",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/e79/7a880a68e991985f73fb228051334e79.jpeg",
        "ingredients": "french fries, cheddar cheese seasoning, tartar sauce, pickled mayo",
        "protein": "low",
        "fat": "medium",
        "energy": "high",
        "carbohydrates": "high",
        "sugar_content": "absent",
        "fiber": "low",
        "veg_or_non_veg": "veg",
        "spiciness": "not spicy",
        "cuisine": "american",
        "meal_time": "snacks",
        "health_concious_option": "no",
        "allergens_present": "dairy",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "yes",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "no",
        "is_gluten_free": "not applicable",
        "is_keto_friendly": "no",
        "is_low_gi": "no",
        "meal_course_type": "small plates"
      },
      {
        "item_id": 93,
        "restaurant_id": 63471,
        "number_of_people_rated": 15,
        "category": "Burger & Sandwich",
        "name_of_item": "Pulled Pork Sandwich",
        "cost": 510,
        "rating": 4.3,
        "description": "Pulled smoked pork shoulder, in-house bbq sauce, apple & fennel slaw; ADD ON BACON | FRIED EGG",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/143/dc003bf6a3b7b47415a32cc3beef9143.jpeg",
        "ingredients": "pulled smoked pork shoulder, in-house bbq sauce, apple, fennel slaw, bacon, fried egg",
        "protein": "high",
        "fat": "medium",
        "energy": "high",
        "carbohydrates": "medium",
        "sugar_content": "low",
        "fiber": "low",
        "veg_or_non_veg": "non-veg",
        "spiciness": "not spicy",
        "cuisine": "american",
        "meal_time": "lunch or dinner",
        "health_concious_option": "no",
        "allergens_present": "egg, pork",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "yes",
        "contains_egg": "yes",
        "contains_dairy": "no",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "yes",
        "is_gluten_free": "not applicable",
        "is_keto_friendly": "no",
        "is_low_gi": "no",
        "meal_course_type": "main course"
      }
    ]
  },
  {
    "combo_id": 5,
    "combo_name": "Asian Seafood Feast",
    "combo_item_ids": [
      "94",
      "13",
      "135"
    ],
    "cost": 1680,
    "description": "A seafood-centric Asian meal, with the perfect balance of sweet, spicy, and savory flavors.",
    "discount_pct": 10,
    "discounted_cost": 1512,
    "has_discount": "yes",
    "combo_type": "vip",
    "combo_items": [
      {
        "item_id": 94,
        "restaurant_id": 63471,
        "number_of_people_rated": 121,
        "category": "Small Plates - Asian Non-veg",
        "name_of_item": "Pumpkin Prawns",
        "cost": 610,
        "rating": 4.6,
        "description": "Prawns tossed in a sweet and spicy pumpkin sauce, topped with sesame seeds",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/d31/56f931530b66bccabcb0adf8c45cfd31.jpeg",
        "ingredients": "prawns, pumpkin sauce, sesame seeds, sweet, spicy",
        "protein": "high",
        "fat": "low",
        "energy": "medium",
        "carbohydrates": "medium",
        "sugar_content": "medium",
        "fiber": "absent",
        "veg_or_non_veg": "non-veg",
        "spiciness": "spicy",
        "cuisine": "other asian",
        "meal_time": "lunch or dinner",
        "health_concious_option": "no",
        "allergens_present": "seafood, sesame",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "yes",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "yes",
        "is_gluten_free": "not applicable",
        "is_keto_friendly": "no",
        "is_low_gi": "not applicable",
        "meal_course_type": "small plates"
      },
      {
        "item_id": 13,
        "restaurant_id": 63471,
        "number_of_people_rated": null,
        "category": "Small Plates - Coastal Non-veg",
        "name_of_item": "Butter Garlic Seafood",
        "cost": 560,
        "rating": null,
        "description": "Choice of Seafood, cooked with lots of butter & finely chopped garlic; PRAWN | SEACRAB",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/9eb/758fe024cfc8fc16bdcd12e0a14979eb.jpeg",
        "ingredients": "prawn, seacrab, butter, garlic",
        "protein": "high",
        "fat": "high",
        "energy": "high",
        "carbohydrates": "absent",
        "sugar_content": "absent",
        "fiber": "absent",
        "veg_or_non_veg": "non-veg",
        "spiciness": "not spicy",
        "cuisine": "other",
        "meal_time": "lunch or dinner",
        "health_concious_option": "no",
        "allergens_present": "shellfish, dairy",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "yes",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "yes",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "no",
        "is_gluten_free": "not applicable",
        "is_keto_friendly": "no",
        "is_low_gi": "not applicable",
        "meal_course_type": "small plates"
      },
      {
        "item_id": 135,
        "restaurant_id": 63471,
        "number_of_people_rated": 16,
        "category": "Large Plates - Asian Rice & Noodles",
        "name_of_item": "Udon Noodles In Black Pepper Sauce",
        "cost": 510,
        "rating": 4.6,
        "description": "Thick and chewy udon noodles, stir-fried in a savory black pepper sauce; VEG | DUCK",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/b54/2152cc29c19f308aa10c5bd1f163eb54.jpeg",
        "ingredients": "udon noodles, black pepper sauce, vegetables, duck",
        "protein": "medium",
        "fat": "medium",
        "energy": "high",
        "carbohydrates": "high",
        "sugar_content": "absent",
        "fiber": "medium",
        "veg_or_non_veg": "veg",
        "spiciness": "not spicy",
        "cuisine": "japanese",
        "meal_time": "lunch or dinner",
        "health_concious_option": "no",
        "allergens_present": "gluten",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "yes",
        "is_gluten_free": "no",
        "is_keto_friendly": "no",
        "is_low_gi": "no",
        "meal_course_type": "main course"
      }
    ]
  },
  {
    "combo_id": 6,
    "combo_name": "Asian Vegetarian Adventure",
    "combo_item_ids": [
      "134",
      "69",
      "115"
    ],
    "cost": 1230,
    "description": "A vegetarian Asian adventure with a mix of unique ingredients and a spicy kick to complement the richness of the mock meat and fried rice.",
    "discount_pct": 5,
    "discounted_cost": 1168.5,
    "has_discount": "yes",
    "combo_type": "premium",
    "combo_items": [
      {
        "item_id": 134,
        "restaurant_id": 63471,
        "number_of_people_rated": 4,
        "category": "Small Plates - Asian Veg",
        "name_of_item": "Turnip Cake",
        "cost": 430,
        "rating": 4.8,
        "description": "Turnip & vegetable cake; steamed & fried",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/704/500b59c5b985b40dad0db82ab76dd704.jpeg",
        "ingredients": "turnip, vegetables, steamed, fried, asian, small plates, vegetarian",
        "protein": "low",
        "fat": "low",
        "energy": "medium",
        "carbohydrates": "medium",
        "sugar_content": "absent",
        "fiber": "high",
        "veg_or_non_veg": "veg",
        "spiciness": "not spicy",
        "cuisine": "other asian",
        "meal_time": "snacks",
        "health_concious_option": "yes",
        "allergens_present": "none",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "yes",
        "is_sattvic": "yes",
        "is_jain_food": "yes",
        "is_dairy_free": "yes",
        "is_gluten_free": "not sure",
        "is_keto_friendly": "not applicable",
        "is_low_gi": "not applicable",
        "meal_course_type": "small plates"
      },
      {
        "item_id": 69,
        "restaurant_id": 63471,
        "number_of_people_rated": null,
        "category": "Small Plates - Asian Veg",
        "name_of_item": "Mock Meat And Vegetables In Mountain Chilli Sauce",
        "cost": 490,
        "rating": null,
        "description": "Mock meat with carrots, mushrooms & beans wok-tossed in a mountain chilli sauce",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/cdc/9e757339801bcc69a239c1adf8f5bcdc.jpeg",
        "ingredients": "mock meat, carrots, mushrooms, beans, mountain chilli sauce",
        "protein": "medium",
        "fat": "low",
        "energy": "medium",
        "carbohydrates": "medium",
        "sugar_content": "absent",
        "fiber": "high",
        "veg_or_non_veg": "veg",
        "spiciness": "spicy",
        "cuisine": "other asian",
        "meal_time": "lunch or dinner",
        "health_concious_option": "yes",
        "allergens_present": "none",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "yes",
        "is_sattvic": "not applicable",
        "is_jain_food": "not applicable",
        "is_dairy_free": "yes",
        "is_gluten_free": "not applicable",
        "is_keto_friendly": "not applicable",
        "is_low_gi": "not applicable",
        "meal_course_type": "small plates"
      },
      {
        "item_id": 115,
        "restaurant_id": 63471,
        "number_of_people_rated": null,
        "category": "Large Plates - Asian Rice & Noodles",
        "name_of_item": "Spicy Fried Rice",
        "cost": 310,
        "rating": null,
        "description": "Stir-fried rice infused with fiery spices, soya sauce, sweet corn & shiitake mushrooms",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/539/706e07fcb79794ffdaff9a3d19c0d539.jpeg",
        "ingredients": "fried rice, spices, soya sauce, sweet corn, shiitake mushrooms, asian cuisine, large plates, rice and noodles, spicy",
        "protein": "low",
        "fat": "medium",
        "energy": "medium",
        "carbohydrates": "high",
        "sugar_content": "low",
        "fiber": "medium",
        "veg_or_non_veg": "veg",
        "spiciness": "spicy",
        "cuisine": "other asian",
        "meal_time": "lunch or dinner",
        "health_concious_option": "no",
        "allergens_present": "soy",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "yes",
        "is_gluten_free": "not applicable",
        "is_keto_friendly": "no",
        "is_low_gi": "not applicable",
        "meal_course_type": "main course"
      }
    ]
  },
  {
    "combo_id": 7,
    "combo_name": "Coastal Indian Experience",
    "combo_item_ids": [
      "65",
      "140",
      "79"
    ],
    "cost": 1019,
    "description": "A coastal Indian experience featuring rich and spicy flavors with delicate and soft Neer Dosa to complement the Kundapur-style curry.",
    "discount_pct": 0,
    "discounted_cost": 1019,
    "has_discount": "no",
    "combo_type": "standard",
    "combo_items": [
      {
        "item_id": 65,
        "restaurant_id": 63471,
        "number_of_people_rated": null,
        "category": "Small Plates - Coastal Non-veg",
        "name_of_item": "Mangalorean Style Sukka",
        "cost": 460,
        "rating": null,
        "description": "Choice of Meat or Seafood, Coated with a mix of fresh & dry coconut & spices; CHICKEN | LAMB",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/9b2/a36a8020484c7d2d38b57f83adf4b9b2.jpeg",
        "ingredients": "meat, seafood, fresh coconut, dry coconut, spices, chicken, lamb",
        "protein": "high",
        "fat": "medium",
        "energy": "medium",
        "carbohydrates": "low",
        "sugar_content": "absent",
        "fiber": "absent",
        "veg_or_non_veg": "non-veg",
        "spiciness": "moderately spicy",
        "cuisine": "indian",
        "meal_time": "lunch or dinner",
        "health_concious_option": "no",
        "allergens_present": "coconut",
        "contains_chicken": "yes",
        "contains_beef": "no",
        "contains_mutton": "yes",
        "contains_seafood": "yes",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "yes",
        "is_gluten_free": "not applicable",
        "is_keto_friendly": "not sure",
        "is_low_gi": "not applicable",
        "meal_course_type": "small plates"
      },
      {
        "item_id": 140,
        "restaurant_id": 63471,
        "number_of_people_rated": null,
        "category": "Large Plates Coastal - Non-Veg ",
        "name_of_item": "Kundapur Chicken Curry",
        "cost": 460,
        "rating": null,
        "description": "South Indian dish featuring tender chicken cooked in a rich coconut-based gravy, seasoned with aromatic spices ",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/36e/b0e8e6b2d84e81b015b65952c685336e.jpeg",
        "ingredients": "chicken, coconut, spices, curry leaves, onion, garlic, ginger, tomato",
        "protein": "high",
        "fat": "medium",
        "energy": "medium",
        "carbohydrates": "low",
        "sugar_content": "absent",
        "fiber": "low",
        "veg_or_non_veg": "non-veg",
        "spiciness": "spicy",
        "cuisine": "indian",
        "meal_time": "lunch or dinner",
        "health_concious_option": "no",
        "allergens_present": "coconut",
        "contains_chicken": "yes",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "yes",
        "is_gluten_free": "yes",
        "is_keto_friendly": "no",
        "is_low_gi": "no",
        "meal_course_type": "main course"
      },
      {
        "item_id": 79,
        "restaurant_id": 63471,
        "number_of_people_rated": 399,
        "category": "Large Plates - Indian Breads & Rice",
        "name_of_item": "Neer Dosa",
        "cost": 99,
        "rating": 4.4,
        "description": "A specialty from coastal Karnataka, delicate, paper-thin crepes made from rice batter",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/bee/805e469cd83978c682f8819bbabfdbee.jpeg",
        "ingredients": "rice batter, water",
        "protein": "absent",
        "fat": "absent",
        "energy": "low",
        "carbohydrates": "medium",
        "sugar_content": "absent",
        "fiber": "low",
        "veg_or_non_veg": "veg",
        "spiciness": "not spicy",
        "cuisine": "indian",
        "meal_time": "anytime",
        "health_concious_option": "yes",
        "allergens_present": "none",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "yes",
        "is_sattvic": "yes",
        "is_jain_food": "not applicable",
        "is_dairy_free": "yes",
        "is_gluten_free": "yes",
        "is_keto_friendly": "yes",
        "is_low_gi": "not sure",
        "meal_course_type": "main course"
      }
    ]
  },
  {
    "combo_id": 8,
    "combo_name": "Classic North Indian Delight",
    "combo_item_ids": [
      "73",
      "10",
      "78"
    ],
    "cost": 1029,
    "description": "A North Indian classic with creamy textures and mildly spiced dishes, perfect for those who enjoy rich flavors without much heat.",
    "discount_pct": 0,
    "discounted_cost": 1029,
    "has_discount": "no",
    "combo_type": "standard",
    "combo_items": [
      {
        "item_id": 73,
        "restaurant_id": 63471,
        "number_of_people_rated": 133,
        "category": "Small Plates - Indian / Tandoor Non-veg",
        "name_of_item": "Murgh Malai Tikka",
        "cost": 470,
        "rating": 4.1,
        "description": "Chicken marinated in a creamy mixture of yogurt, cream, and spices",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/806/d9ed21ca6699756c757abc6edef6a806.jpeg",
        "ingredients": "chicken, yogurt, cream, spices",
        "protein": "high",
        "fat": "medium",
        "energy": "medium",
        "carbohydrates": "absent",
        "sugar_content": "absent",
        "fiber": "absent",
        "veg_or_non_veg": "non-veg",
        "spiciness": "not spicy",
        "cuisine": "indian",
        "meal_time": "anytime",
        "health_concious_option": "no",
        "allergens_present": "dairy",
        "contains_chicken": "yes",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "yes",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "no",
        "is_gluten_free": "yes",
        "is_keto_friendly": "no",
        "is_low_gi": "not applicable",
        "meal_course_type": "small plates"
      },
      {
        "item_id": 10,
        "restaurant_id": 63471,
        "number_of_people_rated": 78,
        "category": "Large Plates - Indian Non-veg",
        "name_of_item": "Butter Chicken",
        "cost": 460,
        "rating": 3,
        "description": "Succulent pieces of pulled tandoori chicken cooked in a creamy and rich makhani gravy, finishing with butter",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/525/6cf99c263b9060eb00346587c1e68525.jpeg",
        "ingredients": "tandoori chicken, makhani gravy, butter, cream, spices",
        "protein": "high",
        "fat": "high",
        "energy": "high",
        "carbohydrates": "low",
        "sugar_content": "absent",
        "fiber": "absent",
        "veg_or_non_veg": "non-veg",
        "spiciness": "not spicy",
        "cuisine": "indian",
        "meal_time": "dinner",
        "health_concious_option": "no",
        "allergens_present": "dairy",
        "contains_chicken": "yes",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "yes",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "no",
        "is_gluten_free": "not applicable",
        "is_keto_friendly": "no",
        "is_low_gi": "not applicable",
        "meal_course_type": "main course"
      },
      {
        "item_id": 78,
        "restaurant_id": 63471,
        "number_of_people_rated": 26,
        "category": "Large Plates - Indian Breads & Rice",
        "name_of_item": "Naan",
        "cost": 99,
        "rating": 3.9,
        "description": "Soft and fluffy bread, freshly baked in a tandoor oven. PLAIN | BUTTER | GARLIC | AFGHAN | KHAMIRI",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/2a7/b6af7215d09ce9bfc3a7bbeabefc82a7.jpeg",
        "ingredients": "naan, tandoor, plain, butter, garlic, afghan, khamiri, bread",
        "protein": "low",
        "fat": "medium",
        "energy": "medium",
        "carbohydrates": "high",
        "sugar_content": "absent",
        "fiber": "low",
        "veg_or_non_veg": "veg",
        "spiciness": "not applicable",
        "cuisine": "indian",
        "meal_time": "anytime",
        "health_concious_option": "no",
        "allergens_present": "gluten, dairy",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "yes",
        "is_vegan": "no",
        "is_sattvic": "yes",
        "is_jain_food": "no",
        "is_dairy_free": "no",
        "is_gluten_free": "no",
        "is_keto_friendly": "no",
        "is_low_gi": "no",
        "meal_course_type": "not applicable"
      }
    ]
  },
  {
    "combo_id": 9,
    "combo_name": "Spicy Indian Tandoori & Curry Combo",
    "combo_item_ids": [
      "72",
      "76",
      "123"
    ],
    "cost": 1159,
    "description": "A fiery combo featuring spicy tandoori chicken and a hearty mutton curry, perfectly paired with tandoori roti for a full-bodied meal.",
    "discount_pct": 0,
    "discounted_cost": 1159,
    "has_discount": "no",
    "combo_type": "standard",
    "combo_items": [
      {
        "item_id": 72,
        "restaurant_id": 63471,
        "number_of_people_rated": 54,
        "category": "Small Plates - Indian / Tandoor Non-veg",
        "name_of_item": "Murgh Angaar Tikka",
        "cost": 440,
        "rating": 4.1,
        "description": "Spicy and flavorful chicken marinated in a blend of spices, gram flour cooked in a tandoor",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/3b0/26475725d8b0b9bfd064cc63ea1b73b0.jpeg",
        "ingredients": "chicken, spices, gram flour",
        "protein": "high",
        "fat": "medium",
        "energy": "medium",
        "carbohydrates": "low",
        "sugar_content": "absent",
        "fiber": "low",
        "veg_or_non_veg": "non-veg",
        "spiciness": "spicy",
        "cuisine": "indian",
        "meal_time": "snacks",
        "health_concious_option": "no",
        "allergens_present": "none",
        "contains_chicken": "yes",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "yes",
        "is_gluten_free": "no",
        "is_keto_friendly": "no",
        "is_low_gi": "no",
        "meal_course_type": "small plates"
      },
      {
        "item_id": 76,
        "restaurant_id": 63471,
        "number_of_people_rated": 51,
        "category": "Large Plates - Indian Non-veg",
        "name_of_item": "Mutton Rogan Josh",
        "cost": 620,
        "rating": 2.7,
        "description": "A classic Kashmiri dish featuring tender mutton simmered in aromatic gravy, with traditional spices like fennel, ginger, and Kashmiri red chilli",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/0b2/b6a57cf0c0493b48f6f2bab9943500b2.jpeg",
        "ingredients": "mutton, aromatic gravy, fennel, ginger, kashmiri red chilli",
        "protein": "high",
        "fat": "medium",
        "energy": "high",
        "carbohydrates": "low",
        "sugar_content": "absent",
        "fiber": "absent",
        "veg_or_non_veg": "non-veg",
        "spiciness": "spicy",
        "cuisine": "indian",
        "meal_time": "dinner",
        "health_concious_option": "no",
        "allergens_present": "none",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "yes",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "no",
        "is_sattvic": "no",
        "is_jain_food": "no",
        "is_dairy_free": "yes",
        "is_gluten_free": "not applicable",
        "is_keto_friendly": "yes",
        "is_low_gi": "not applicable",
        "meal_course_type": "main course"
      },
      {
        "item_id": 123,
        "restaurant_id": 63471,
        "number_of_people_rated": 26,
        "category": "Large Plates - Indian Breads & Rice",
        "name_of_item": "Tandoori Roti",
        "cost": 85,
        "rating": 4.2,
        "description": "Traditional Indian flatbread cooked in a tandoor oven. PLAIN | BUTTER",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/cf6/32020deefb8cad1da9c342e91edf7cf6.jpeg",
        "ingredients": "tandoori roti, flatbread, indian, tandoor oven, plain, butter",
        "protein": "low",
        "fat": "medium",
        "energy": "medium",
        "carbohydrates": "high",
        "sugar_content": "absent",
        "fiber": "low",
        "veg_or_non_veg": "veg",
        "spiciness": "not applicable",
        "cuisine": "indian",
        "meal_time": "anytime",
        "health_concious_option": "no",
        "allergens_present": "dairy",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "yes",
        "is_vegan": "no",
        "is_sattvic": "yes",
        "is_jain_food": "no",
        "is_dairy_free": "no",
        "is_gluten_free": "no",
        "is_keto_friendly": "no",
        "is_low_gi": "no",
        "meal_course_type": "not applicable"
      }
    ]
  },
  {
    "combo_id": 10,
    "combo_name": "Vegetarian North Indian Comfort",
    "combo_item_ids": [
      "35",
      "143",
      "101"
    ],
    "cost": 949,
    "description": "A rich, comforting vegetarian combo with creamy textures and soft, fluffy bread.",
    "discount_pct": 0,
    "discounted_cost": 949,
    "has_discount": "no",
    "combo_type": "standard",
    "combo_items": [
      {
        "item_id": 35,
        "restaurant_id": 63471,
        "number_of_people_rated": 119,
        "category": "Small Plates - Indian / Tandoor Veg",
        "name_of_item": "Dahi Ke Kebab",
        "cost": 410,
        "rating": 4.1,
        "description": "A signature, soft and creamy kebabs made with in-house ricotta cheese, raisins, crumbed and deep fried until golden crispy",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/a8e/d0888ff9776f1bb1cf3e3b4c25934a8e.jpeg",
        "ingredients": "ricotta cheese, raisins, breadcrumbs, spices, oil",
        "protein": "medium",
        "fat": "medium",
        "energy": "medium",
        "carbohydrates": "medium",
        "sugar_content": "low",
        "fiber": "low",
        "veg_or_non_veg": "veg",
        "spiciness": "not spicy",
        "cuisine": "indian",
        "meal_time": "snacks",
        "health_concious_option": "no",
        "allergens_present": "dairy",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "yes",
        "is_vegan": "no",
        "is_sattvic": "not applicable",
        "is_jain_food": "not applicable",
        "is_dairy_free": "no",
        "is_gluten_free": "not sure",
        "is_keto_friendly": "no",
        "is_low_gi": "not applicable",
        "meal_course_type": "small plates"
      },
      {
        "item_id": 143,
        "restaurant_id": 63471,
        "number_of_people_rated": 16,
        "category": "Large Plates - Indian Veg ",
        "name_of_item": "Kadai Paneer",
        "cost": 440,
        "rating": 4.1,
        "description": "Malai paneer & assorted vegetables cooked with Indian spices; best eaten with tandoori roti",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/fd3/a53cb42c76b9ffbd36ee8d2f0c0dcfd3.jpeg",
        "ingredients": "malai paneer, assorted vegetables, indian spices, tandoori roti",
        "protein": "medium",
        "fat": "medium",
        "energy": "medium",
        "carbohydrates": "medium",
        "sugar_content": "absent",
        "fiber": "medium",
        "veg_or_non_veg": "veg",
        "spiciness": "moderately spicy",
        "cuisine": "indian",
        "meal_time": "lunch or dinner",
        "health_concious_option": "yes",
        "allergens_present": "dairy",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "yes",
        "is_vegan": "no",
        "is_sattvic": "yes",
        "is_jain_food": "no",
        "is_dairy_free": "no",
        "is_gluten_free": "no",
        "is_keto_friendly": "no",
        "is_low_gi": "no",
        "meal_course_type": "main course"
      },
      {
        "item_id": 101,
        "restaurant_id": 63471,
        "number_of_people_rated": 117,
        "category": "Large Plates - Indian Breads & Rice",
        "name_of_item": "Roomali Roti",
        "cost": 99,
        "rating": 4,
        "description": "Thin and soft Indian flatbread",
        "image_link": "https://b.zmtcdn.com/data/dish_photos/951/2f544dade3b6fc38125d81a1ba228951.jpeg",
        "ingredients": "thin and soft indian flatbread",
        "protein": "absent",
        "fat": "absent",
        "energy": "low",
        "carbohydrates": "medium",
        "sugar_content": "absent",
        "fiber": "low",
        "veg_or_non_veg": "veg",
        "spiciness": "not applicable",
        "cuisine": "indian",
        "meal_time": "anytime",
        "health_concious_option": "yes",
        "allergens_present": "none",
        "contains_chicken": "no",
        "contains_beef": "no",
        "contains_mutton": "no",
        "contains_seafood": "no",
        "contains_pork": "no",
        "contains_egg": "no",
        "contains_dairy": "no",
        "is_vegan": "yes",
        "is_sattvic": "yes",
        "is_jain_food": "not applicable",
        "is_dairy_free": "yes",
        "is_gluten_free": "no",
        "is_keto_friendly": "no",
        "is_low_gi": "not applicable",
        "meal_course_type": "not applicable"
      }
    ]
  }
]